[package]
name = "RustySmash"
version = "0.1.0"
authors = ["Keegan Parker <keegandparker@gmail.com>"]

[[bin]]
name = "rusty-smash"

[dependencies]
piston = "0.2.0"
piston_window = "0.5.0"
piston2d-graphics = "0.2.0"
